### ISSUE TITLE
Grease suggestions and motivations

### ISSUE THREAD

**Issue by hardaker** [intarchboard/draft-use-it-or-lose-it#15]
The way the grease section ends leaves it unclear in my mind whether it's being a recommended solution or not.  It feels concluded (and maybe it's just informational, but then stating explicitly that there are pros/cons with this mechanism may help state explicitly that there isn't a conclusion being offered).

It's also unclear why someone would be motivated to actually implement grease at all; what is the gain by doing so unless you're a security scanner?  Why would the average implementation do something like this?  What's their motivation that justifies an increase in complexity (which you specifically point out doesn't happen in typical engineering in "Good Protocol Design is Not Sufficient")?

**Comment by hardaker** [comment]
I like the new text.  But it still doesn't explain what would motivate the average implementation for actually putting the work in (only to actually decrease interoperability temporarily).  In other portions of the document we already state implementors are lazy or trying to push new code quickly, and this is a cost in both $$s, speed and interoperability.  I'm glad it worked for TLS, but what motivated people to do it?  Or was that "things had gotten so bad we have to do something"; it certainly wasn't at the start of the protocol, ie.

**Comment by martinthomson** [comment]
Doesn't it say that it is done to protect the ability to deploy new extensions in future?  Sure, that's not always a pressing concern, but that depends on how acutely you have felt the pain of not being able to ship an extension.

**Comment by hardaker** [comment]
What market forces are motivated to implement and deploy it?  Logically, I understand why it's useful.  I understand less why real-world folks would be willing to take the time and energy to do implement it.  IE, theory: understood.  Practical: I don't see motivation for software writers that could be justified to management easily.

**Comment by martinthomson** [comment]
I don't think that this is justified on such simple or direct terms.  You probably have to look to the concept of merit goods if you want to get into economics here.  After all, the benefit is not necessarily something that the implementer sees, it's one that the community as a whole sees (or might see) in the fullness of time.

After all, if you couch a question about deploying encryption in the same way, you might have similar trouble in justification.  The answer is usually tied into hedging strategies against the risk of future problems.  

For example, you might reasonably say that making cleartext DNS queries in most networks is benign.  And the cost of deploying encryption is considerable. More so if you start with the understanding that most network operators accord those requests with due respect, including taking every effort to ensure that they are the only ones that see those packets.  If you consider the breadth of possible networks and the span of time, the occasional instances of failures in that regard might lead to a different risk assessment.

Collectively, the QUIC working group has expended significant energy on this general question.  This is in part because of a deeper understanding of the risk profile in that environment.  This stuff really does happen.  I don't know if I recounted the story about Google's QUIC breaking a few years ago due to bad assumptions made about the semantics of a key protocol element.  Add the scars from multiple bad experiences with TLS and you might appreciate that there is some desire to address the problem proactively.

Of course, even with the desire to protect future extensibility, there is some justified skepticism about the efficacy of greasing as a general mechanism.  I hope that this document has captured that.
