### ISSUE TITLE
Correct or fail

### ISSUE THREAD

**Issue by martinthomson** [intarchboard/draft-use-it-or-lose-it#28]
One of the nice innovations in the design of TLS 1.3 was the inclusion of mechanisms that ensured that correct implementation of a feature was necessary for interoperation.  Including mention of this in the "dependency" chapter would be great.  The key element here is creating a mechanism where defection by one entity results in changes to keys, and so a mistake in implementation would result in an inability to communicate.

I can't recall the specific mechanism, but the QUIC Initial encryption is an example of this.

**Comment by martinthomson** [comment]
The more I think about this, the less enthusiastic I am about including it.  It feels like a digression into other areas of protocol design.  These tricks are intended to ensure that both peers agree by encoding that agreement into functions that are critical to protocol operation, like the derivation of encryption keys or the TLS finished.  We've learned that these tricks can be useful and can even improve protocol efficiency by allowing validation of agreement without exchanging data (see the QUIC Retry authentication), but they don't necessarily apply to the central theme of this draft.

**Comment by tfpauly** [comment]
I think this may still be relevant to include this point in some form, although I agree with your assessment that it may not be appropriate as a top-level argument.

If we're discussing how version negotiation is particularly prone to ossification, a recommendation that comes out of that is that it can be done in some other protocol's extension layer (ALPN, as the primary example). It would be good to point out at this moment that the mechanism selected for doing version negotiation really ought to be one that has integrity checks and authentication (like how TLS folds in the transcript hash) rather than a useful extension mechanism that could lead to downgrade attacks.

**Comment by martinthomson** [comment]
I'd be interested to see how you might fit something like that in.  I appreciate that the interaction of downgrade protection with version negotiation makes it more challenging than otherwise (see QUIC discussions), but I'm still concerned that it would end up being a digression rather than contributing to the central theme.

**Comment by tfpauly** [comment]
Not to be included in the doc, based on discussion.
