### ISSUE TITLE
Appendex A.1: BGP

### ISSUE THREAD

**Issue by elear** [intarchboard/draft-use-it-or-lose-it#72]
There's not enough information to understand what happened and how this draft pertains to addressing the BGP failure.  For one thing, the reference [RIPE-99] has a reference to a Cisco URL that apparently no longer exists; IOS-XR at that time was brand spanking new.  And it's not like BGP extensions weren't a regular thing at that time.

However, there is a different use case that might be interesting to pursue: partial deployment of ROAs  and S*BGP led to some unintended consequences.  See [Lychev, Goldberg, Shapira](https://arxiv.org/abs/1307.2690).  This gets into multiparty aspects.

**Comment by martinthomson** [comment]
As an example, I think that this is sufficient.  Bad link notwithstanding... (see <https://www.w3.org/Provider/Style/URI.html>).

This isn't saying that the problem is constant or that BGP can't change, but that BGP, like many other protocols, has experienced the same sorts of issues too.

I read the paper; it's good work, but I'm not seeing the relevance.  It is primarily about deployment incentives and how various amounts of deployment might contribute to security goals.

**Comment by elear** [comment]
The issue with BGP is that changes to one router's routing table can impact an entire system.  And so protocol options used between two routers can have an impact beyond those two routers.  I am suspecting what you are seeing is a bug of that variety.

**Comment by martinthomson** [comment]
I've dropped the BGP example.  As you noted privately, it doesn't really support any particular advice in the document, it just existed and that's bloat.
